### ISSUE TITLE
Is there a timetable for a new release?

### ISSUE THREAD

**Issue by Rongronggg9** [kurtmckee/listparser#4]
Hi there.

The release history of `listparser` has been radio-silent for 7 years.

I am the author of https://github.com/Rongronggg9/RSS-to-Telegram-Bot. My project, published to PyPI using the package name [`rsstt`](https://pypi.org/project/rsstt/), depends on `listparser`. I really love the current unreleased version and would like to upgrade to it. However, packages published to PyPI are not allowed to depend on packages outside PyPI. And I would neither like to publish my own `listparser` package nor like to bundle it inside my package, unless I have to.

That might be a somewhat rude question, but could I ask that is there a timetable for a new release?

**Comment by kurtmckee** [comment]
Thank you for the praise, and for the nudge! I've released listparser 0.19 to PyPI.

If you encounter any bugs, or have suggestions for improvement, please don't hesitate to file more issues! 😀 

Have a great weekend!

**Comment by Rongronggg9** [comment]
Hi Kurt, 

The release is nice but an API change seems undocumented: `parse()` no longer accepts file-like `parse_obj`.

Could you fix the release note and/or changelog to document it?

Have a cute weekend!

Related: https://github.com/Rongronggg9/RSS-to-Telegram-Bot/pull/89
