### ISSUE TITLE
Expose both `feed.title` and `feed.text`

### ISSUE THREAD

**Issue by Rongronggg9** [kurtmckee/listparser#71]
`listparser` only exposes `feed.title`. It will be the `text` attribute of an `outline`, or, if unavailable, the `title` attribute.

https://github.com/kurtmckee/listparser/blob/05bec3a51d8519c58566fed1e2095d0efd86783a/docs/reference/object-title.rst?plain=1#L16-L19

However, OPML 2.0 marks the `text` attribute as mandatory.

https://github.com/kurtmckee/listparser/blob/05bec3a51d8519c58566fed1e2095d0efd86783a/docs/specifications/opml-2.0.rst?plain=1#L110

https://github.com/kurtmckee/listparser/blob/05bec3a51d8519c58566fed1e2095d0efd86783a/docs/specifications/opml-2.0.rst?plain=1#L155

As a result, if an RSS reader adheres OPML 2.0, the exported OPML may have both `tilte` and `text` even if there is no user-defined feed title. 

I propose that `listparser` exposes `feed.title` (keep the current behavior), `feed.title_orig`, and `feed.text`, so that the above case can be identified by determining if `feed.title_orig == feed.text`.

**Comment by Rongronggg9** [comment]
> I only want it to expose information that feed readers need to import the user's title/catorgery/tag information.

I agree with that. But does the current behavior really provide enough "information that feed readers need to import the user's title"? Why is it important to determine if the title is user-defined or not? Can't the feed reader just fetch the feed once, and then compare its title with `feed.title` from `listparser`? Let's imagine such a case:

1. Some feeds occasionally update their title ("remote title").
2. An RSS reader may be implemented to follow the remote title change unless users have defined their custom title.
3. A user exports OPML from the RSS reader as a backup. Each feed's `outline` comes with `text` attr (user-defined title, if available, else feed title) and `title` attr (always feed title).
4. Days later, some of these feeds happen to update their titles.
5. The user imports the OPML into the RSS reader on a new device.
6. If we can only compare `feed.title` from `listparser` with the fetched title ("remote title"), since they differ, `feed.title` from `listparser` can only be considered as user-defined. As a result, it will override the remote title. The user may consider this an undesired behavior if they want the title in the RSS reader to follow the remote one every day.
7. My proposal is a solution to the above case.

I admit that the case may be an edge case. If you consider it "out of `listparser`'s business", nevermind :)

**Comment by kurtmckee** [comment]
I think I understand your use case now, and I appreciate the example case you provided!

However, I don't think listparser should help resolve this issue.
